
FROM node:lts-alpine AS build


WORKDIR /usr/src/app


COPY ["package.json", "package-lock.json*", "./"]


RUN npm install


COPY . .


RUN npm run build


FROM node:lts-alpine


WORKDIR /usr/src/app


COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY package.json .


ENV NODE_ENV=production
ENV DATABASE_URL=mongodb://mongo-database:27017
ENV DATABASE_NAME=TopicstoreDb
ENV HOST=0.0.0.0
ENV PORT=5000


EXPOSE 5000


CMD ["npm", "start"]
